version: '3'
services:
  react:
    build : .
    restart: unless-stopped
    privileged: true
    container_name: react
    command : service nginx restart && npm run dev
    # command : tail -f /dev/null
    hostname: root
    volumes:
      - ./components:/usr/src/app/components
      - ./pages:/usr/src/app/pages
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
###
