version: "3.7"
services:
  react:
    healthcheck:
      test: ["CMD","curl","-f", "http://localhost:3000",]
      interval: 1s
      retries: 30
      start_period: 60s
    build: .
    container_name: react
    user: root
    entrypoint: npm run dev
    volumes:
      - ./components:/usr/src/app/components
      - ./pages:/usr/src/app/pages
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./next.config.js:/usr/src/app/next.config.js
    ports:
      - 3000:3000
    restart: unless-stopped