import A from "./tabs/First";
import B from "./tabs/Second";
import F from "./tabs/Third";
import C from "./components/AutoComplete";
import D from "./components/CustomOptions";
import E from "./components/ListSetter";
import UCE, { UCECB } from "./functions/useCustomEffect";

import CodeModule from "./components/Code";
import h_Check from "./tabs/Fourth";
export const Essentials = A;
export const PortVolumes = B;
export const NetworksETC = F;
export const CustomAutoComplete = C;
export const CustomOptions = D;
export const ListSetter = E;
export const useCustomEffect = UCE;
export const Code = CodeModule;
export const HealthCheck = h_Check;
export const useCustomEffectCallBack = UCECB;
